### ISSUE TITLE
Create example that benefits from follower reads

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/movr#56]

**Comment by nstewart** [comment]
@piyush-singh adding you as the owner here. I know there are some open questions about how to do "as of system time" with an ORM. Do we have any best practices here @rmloveland @awoods187 ?

**Comment by nstewart** [comment]
`Server version: CockroachDB CCL v19.1.2 (x86_64-apple-darwin14, built 2019/06/07 17:27:01, go1.11.6) (same version as client)`

I started attempting to use this feature in MovR https://github.com/cockroachdb/movr/blob/follower-reads/movr.py#L115

But I'm running into this error 
```
2019-08-24 11:23:48,384 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-08-24 11:23:48,384 INFO sqlalchemy.engine.base.Engine SAVEPOINT cockroach_restart
2019-08-24 11:23:48,384 INFO sqlalchemy.engine.base.Engine {}
2019-08-24 11:23:48,385 INFO sqlalchemy.engine.base.Engine select city, id from vehicles AS OF SYSTEM TIME experimental_follower_read_timestamp() where city=%(city)s
2019-08-24 11:23:48,385 INFO sqlalchemy.engine.base.Engine {'city': 'new york'}
2019-08-24 11:23:48,386 INFO sqlalchemy.engine.base.Engine ROLLBACK TO SAVEPOINT cockroach_restart
2019-08-24 11:23:48,386 INFO sqlalchemy.engine.base.Engine {}
2019-08-24 11:23:48,386 INFO sqlalchemy.engine.base.Engine ROLLBACK
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.InternalError: inconsistent AS OF SYSTEM TIME timestamp. Expected: 1566660228.385016000,0. Generally AS OF SYSTEM TIME cannot be used inside a transaction.
```

If I try to run this outside of a session, just using engine.execute() I get the same error:
```
>>> m.get_vehicles("new york", follower_read=True)
2019-08-24 11:06:58,946 INFO sqlalchemy.engine.base.Engine select city, id from vehicles AS OF SYSTEM TIME experimental_follower_read_timestamp() where city=%(city)s
2019-08-24 11:06:58,948 INFO sqlalchemy.engine.base.Engine {'city': 'new york'}
2019-08-24 11:06:58,950 INFO sqlalchemy.engine.base.Engine ROLLBACK
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
    context)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
psycopg2.InternalError: inconsistent AS OF SYSTEM TIME timestamp. Expected: 1566659218.949130000,0. Generally AS OF SYSTEM TIME cannot be used inside a transaction.
```

@awoods187 @jordanlewis any idea? cc @ajwerner

**Comment by jordanlewis** [comment]
Looks like the problem is that you can't use `AS OF SYSTEM TIME` in a transaction, but that's not permitted. Can you configure sqlalchemy to not create transactions? Sometimes that's called "autocommit".

**Comment by jseldess** [comment]
Actually, you can use AOST in a transaction, if you can make it explicit: https://www.cockroachlabs.com/docs/stable/as-of-system-time.html#using-as-of-system-time-in-transactions

**Comment by nstewart** [comment]
@jordanlewis - I tried removing the trasnaction (see the second trace) and still got the same error. To do that I tried AOST without the `session` object and used the `engine` object to query directly (the second trace doesn't have a `BEGIN`). 

I'll explore auto commit, but it looks like the second attempt did not create a transaction based on the logs.

**Comment by nstewart** [comment]
Jesse -- that worked. I'll create tickets to
1) fix the usability issue in CRDB with the misleading error message and 
2) call out how to use this in an ORM.
